# Test various things

@github_token=xxx

## Fetch _site.json locally
GET http://127.0.0.1:3000/sitejson


## Fetch user's repos
GET https://api.github.com/users/barrettotte/repos
Accept: application/vnd.github.v3+json


POST https://api.github.com/graphql
Authorization: Bearer {{github_token}}

{
    "query": "{repository(owner:\"barrettotte\", name:\"MTM-2019\"){createdAt description languages(first: 5){nodes{name}} name updatedAt url}}"
}
