# Testing fetching a gist with HTTP

@base=https://api.github.com
@username=barrettotte
@gist_id=ee6348040d495ad2ab19bc40fbcff6be

### https://api.github.com/gists/ee6348040d495ad2ab19bc40fbcff6be


### List of gists
GET {{base}}/users/{{username}}/gists HTTP/1.1


### Get specific gist
GET {{base}}/gists/{{gist_id}} HTTP/1.1


### Get specific raw file
GET https://gist.githubusercontent.com/{{username}}/{{gist_id}}/raw/index.json HTTP/1.1
