# 
query{
  user(login: "barrettotte"){
    repositories(first: 100, isFork: false){
      nodes{ 
        name 
        description 
        url 
        languages(first: 4){
          nodes{
            name
          }
        }
        updatedAt
      }
    }
  }
}