# Cron task to update projects.json gist based on github repos and override.json

name: Update projects.json in gist

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./github
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.working-directory }}

      - name: Run script
        run: npm run start
        working-directory: ${{ env.working-directory }}
        env:
          GITHUB_TOKEN :  ${{ secrets.GITHUB_TOKEN }}
